services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  webserver:
    networks_mode: bridge
    volumes:
      - static:/static
    env_file:
      - .env
    build: .
    restart: always
    ports:
      - "44445:8000"
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/static
    ports:
      - "44444:80"
    depends_on:
      - webserver

volumes:
  static: